<a href="https://colab.research.google.com/github/RiderKick2204/CS523.M21.KHCL/blob/main/Numpy_version0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math
import numpy as np
import pandas as pd
from operator import mul
from functools import reduce 

#**Size**


In [ ]:
def get_size(L):
  if (type(L)==list):
    return len(L) * get_size(L[0])
  else:
    return 1

#**Shape**

In [ ]:
def get_shape(L,shape=()):
  if (type(L)!=list):
    return shape
  if (type(L[0])==list):
    Len_of_sublist = len(L[0])
    for i in range(len(L)):
      if (len(L[i])!=Len_of_sublist):
        raise ValueError("All lists not have same length")
        break
  shape = get_shape(L[0],shape + (len(L),))
  return shape

In [ ]:
L = [[[2,3],[2,4],[2,7]],[[2,5],[2,6],[2,8]]]
get_shape(L)

(2, 3, 2)

#**Array_split**

In [ ]:
def Array_split(L,indices_or_sections):
  if (indices_or_sections <= 0):
    raise ValueError("number sections must be larger than 0.")
  if (indices_or_sections == 1):
    return L
  T = []
  Length = len(L)
  if (indices_or_sections > len(L)):
    parts = 1
  else:
    parts = len(L) // indices_or_sections + len(L) % indices_or_sections
  for i in range(indices_or_sections):
    T.append(L[max(i*parts,0):min(Length,(i+1)*parts)])
  return T

In [ ]:
Arr = np.random.randint(1,10,(2,3,4))

In [ ]:
A = np.arange(1,17).reshape(2,2,2,2)
indices_or_sections = 5
print("Array A")
print(A)
print("Using numpy.array_split:")
print(pd.Series(data=np.array_split(A,indices_or_sections)))
D = A.tolist()
print("Without using numpy.array_split:")
print("Current: ",D)
print("Array_split(A,{}):".format(indices_or_sections))
print(pd.Series(data=Array_split(D,indices_or_sections)))
D = np.asarray(D)

Array A
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
Using numpy.array_split:
0            [[[[1 2], [3 4]], [[5 6], [7 8]]]]
1    [[[[ 9 10], [11 12]], [[13 14], [15 16]]]]
2                                            []
3                                            []
4                                            []
dtype: object
Without using numpy.array_split:
Current:  [[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]]
Array_split(A,5):
0           [[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]]
1    [[[[9, 10], [11, 12]], [[13, 14], [15, 16]]]]
2                                               []
3                                               []
4                                               []
dtype: object


#**Reshape**

In [ ]:
def Reshape(L,shape=()):
  newsize = 1
  newdim = 0
  T = L
  if not isinstance(shape,(tuple,list)):
    newsize = shape
    newdim = 1
  else:
    newsize = 1
    for x in list(shape):
      newsize = newsize * x
  dim = len(list(get_shape(L)))
  if (newsize != get_size(L)):
    raise ValueError ("cannot reshape array of size {} into shape {}".format(get_size(L),shape))
  for i in range(dim-1):
    T = [a for b in T for a in b]
  if (newdim == 1): 
    return T
  else:
    shape = list(shape)
    shape.reverse()
    for x in range(len(shape)):
      T = Array_split(T,newsize//shape[x])
      newsize //= shape[x]
    return T

In [ ]:
shape = ()
for i in range(15):
 shape += (2,)
shape += (3,)
B = np.arange(1,98305).reshape(shape)
shape = ()
print("Current shape of array: ",B.shape)
print("Current number of dimensions of array:",B.ndim)
for i in range(12):
  shape += (2,)
shape += (12,)
shape += (2,)
# print(len(list(shape)))
print("Reshape to {} dimensions, shape {}".format(len(list(shape)),shape))
D = Reshape(B.tolist(),list(shape))
print("\nReshape without using numpy - storage in list")
print("Shape of list D:",np.array(D).shape)
print("Number of dimensions of list D:",np.array(D).ndim)
B = B.reshape(shape)
print("\nReshape using numpy - storage in array")
print("Shape of array B:",B.shape)
print("Number of dimensions of array B:",B.ndim)
print("\nB = D:",np.array_equal(B,np.array(D)))

Current shape of array:  (2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3)
Current number of dimensions of array: 16
Reshape to 14 dimensions, shape (2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 12, 2)

Reshape without using numpy - storage in list
Shape of list D: (2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 12, 2)
Number of dimensions of list D: 14

Reshape using numpy - storage in array
Shape of array B: (2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 12, 2)
Number of dimensions of array B: 14

B = D: True


In [ ]:
C = np.random.randint(1,10,(5,3,2,2,2,2,2,2))
C.ndim

8

#Transpose

In [ ]:
def Transpose(L):
  T = L
  shape = list(get_shape(T))
  dim = len(shape)
  for i in range(dim-1):
    T = [a for b in T for a in b]
  size = 1
  for i in shape:
    size = size * i
  for i in shape[:-1]:
    size //= i
    new_T = []
    for j in range(size):
      new_T.append([])
      for k in range(i):
        new_T[j] = new_T[j] + [T[j+k*size]]
    T = new_T
  return T

In [ ]:
shape = ()
for i in range(15): 
  shape += (np.random.randint(2,4),)
C2 = np.random.randint(1,1000,shape)
D1 = C2.transpose()
D2 = Transpose(C2.tolist())
print(D1.shape," ",get_shape(D2))
print(np.array_equal(D1,np.array(D2)))

(3, 3, 3, 3, 2, 2, 3, 3, 2, 3, 2, 3, 3, 2, 2)   (3, 3, 3, 3, 2, 2, 3, 3, 2, 3, 2, 3, 3, 2, 2)
True
